=== belaban/IronJacamar/common/src/main/resources/schema/jboss-ra_2_0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.jboss.org/schema/ra"
    xmlns:ra="http://www.jboss.org/schema/ra" xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:javaee="http://java.sun.com/xml/ns/javaee"
    elementFormDefault="qualified" attributeFormDefault="unqualified" version="2.0">

    <xs:element name="jboss-ra" type="ra:jboss-ra-type"/>                              
    
    <xs:complexType name="jboss-ra-type">           
        
        <xs:sequence>
            <xs:element name="ra-config-property" type="ra:ra-config-property-type" minOccurs="0" maxOccurs="unbounded"/>  
            
            <xs:element name="bean-validation-groups" type="ra:bean-validation-groups-type" minOccurs="0" maxOccurs="unbounded"/>

            <xs:element name="bootstrap-context" type="xs:token" minOccurs="0" maxOccurs="1"/> 
        </xs:sequence>
        
    </xs:complexType>
    
    <xs:complexType name="ra-config-property-type">

        <xs:sequence>
            <xs:element name="ra-config-property-name" type="xs:token" minOccurs="1" maxOccurs="1"/>
            <xs:element name="ra-config-property-type" type="ra:ra-config-property-type-type" minOccurs="1" maxOccurs="1"/>
            <xs:element name="ra-config-property-value" type="xs:token" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="override-element" type="ra:override-element-type" default="resourceadapter"/>
    </xs:complexType>

     <xs:complexType name="bean-validation-groups-type">
       <xs:sequence>
         <xs:element name="bean-validation-group" nillable="true" minOccurs="0" maxOccurs="unbounded">
           <xs:complexType>
             <xs:simpleContent>
               <xs:extension base="xs:string">
               </xs:extension>
             </xs:simpleContent>
           </xs:complexType>
         </xs:element>
       </xs:sequence>
     </xs:complexType>
     
      <xs:simpleType name="ra-config-property-type-type">
          <xs:restriction base="xs:token">
            <xs:enumeration value="java.lang.Boolean"/>
            <xs:enumeration value="java.lang.String"/>
            <xs:enumeration value="java.lang.Integer"/>
            <xs:enumeration value="java.lang.Double"/>
            <xs:enumeration value="java.lang.Byte"/>
            <xs:enumeration value="java.lang.Short"/>
            <xs:enumeration value="java.lang.Long"/>
            <xs:enumeration value="java.lang.Float"/>
            <xs:enumeration value="java.lang.Character"/>
          </xs:restriction>
      </xs:simpleType>
      
      <xs:simpleType name="override-element-type">
          <xs:restriction base="xs:token">
            <xs:enumeration value="connection-definition"/>
            <xs:enumeration value="resourceadapter"/>
            <xs:enumeration value="activationspec"/>
            <xs:enumeration value="adminobject"/>
            <xs:enumeration value="authentication-mechanism"/>
          </xs:restriction>
      </xs:simpleType>      
</xs:schema>

=== belaban/IronJacamar/deployers/src/test/resources/ra16standard303jbossra.rar/META-INF/jboss-ra.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- $Id $ -->

<jboss-ra xmlns="http://www.jboss.org/schema/ra"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.jboss.org/schema/ra
          http://www.jboss.org/schema/jboss-ra_2_0.xsd">
   <ra-config-property>
      <ra-config-property-name>myIntProperty</ra-config-property-name>
      <ra-config-property-type>java.lang.Integer</ra-config-property-type>
      <ra-config-property-value>8</ra-config-property-value>
   </ra-config-property>
   
   <ra-config-property override-element="connection-definition">
      <ra-config-property-name>myStringProperty</ra-config-property-name>
      <ra-config-property-type>java.lang.String</ra-config-property-type>
      <ra-config-property-value>newJCA</ra-config-property-value>
   </ra-config-property>   
   
    <ra-config-property override-element="activationspec">
       <ra-config-property-name>myBooleanProperty</ra-config-property-name>
       <ra-config-property-type>java.lang.Boolean</ra-config-property-type>
       <ra-config-property-value>false</ra-config-property-value>
    </ra-config-property>
    
 <bean-validation-groups>
   <bean-validation-group>org.jboss.jca.test.deployers.spec.rars.ra16standard303jbossra.FirstStep</bean-validation-group>
   <bean-validation-group>org.jboss.jca.test.deployers.spec.rars.ra16standard303jbossra.SecondStep</bean-validation-group>
 </bean-validation-groups> 
</jboss-ra>

=== belaban/IronJacamar/common/src/test/resources/jboss-ra-2.0-multiple-attributes.xml
<?xml version="1.0" encoding="UTF-8"?>
<jboss-ra xmlns="http://www.jboss.org/schema/ra/2.0"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.jboss.org/schema/ra/2.0 file:/dati/project/RH/jboss-jca/common/src/main/resources/schema/jboss-ra_2_0.xsd">
    <ra-config-property override-element="resourceadapter">
        <ra-config-property-name>ra-config-property-name0</ra-config-property-name>
        <ra-config-property-type>java.lang.Boolean</ra-config-property-type>
        <ra-config-property-value>ra-config-property-value0</ra-config-property-value>
    </ra-config-property>
    <ra-config-property override-element="resourceadapter">
        <ra-config-property-name>ra-config-property-name1</ra-config-property-name>
        <ra-config-property-type>java.lang.Boolean</ra-config-property-type>
        <ra-config-property-value>ra-config-property-value1</ra-config-property-value>
    </ra-config-property>
    <bean-validation-groups>
        <bean-validation-group>bean-validation-group0</bean-validation-group>
        <bean-validation-group>bean-validation-group1</bean-validation-group>
    </bean-validation-groups>
    <bean-validation-groups>
        <bean-validation-group>bean-validation-group2</bean-validation-group>
        <bean-validation-group>bean-validation-group3</bean-validation-group>
    </bean-validation-groups>
    <bootstrap-context>bootstrap-context0</bootstrap-context>
</jboss-ra>
